/* NightCast Authentication Worker - Debug/Test build
 * Worker: nightcastworks
 * D1 binding: DB -> nightcastdb
 * Debugging is controlled by AUTH_DEBUG=true.
 * Never logs passwords, OTPs, session tokens, CSRF tokens, or secrets.
 */
const CONFIG={
 APP_NAME:"NightCast Authentication",DB_BINDING:"DB",ASSETS_BINDING:"ASSETS",
 COOKIE_NAME:"__Host-auth_session",CSRF_COOKIE:"__Host-auth_csrf",
 SESSION_TTL_SECONDS:60*60*24*7,OTP_TTL_SECONDS:180,OTP_MAX_ATTEMPTS:5,
 PBKDF2_ITERATIONS:310000,PASSWORD_MIN_LENGTH:10,MAX_PASSWORD_LENGTH:256,
 MAX_USERNAME_LENGTH:100,MAX_EMAIL_LENGTH:254,MAX_PHONE_LENGTH:32,
 LOGIN_MAX_FAILURES:8,LOGIN_LOCK_SECONDS:300,CSRF_TTL_SECONDS:3600,
 LOGIN_SUCCESS_REDIRECT:"/dashboard.html",ALLOWED_ORIGINS:[]
};
const enc=new TextEncoder(),dec=new TextDecoder();
const now=()=>new Date().toISOString(); const add=s=>new Date(Date.now()+s*1000).toISOString();
function b64u(x){let s="";for(const b of new Uint8Array(x))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function fromB64u(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
const rand=n=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return a}; const token=(n=32)=>b64u(rand(n)); const uuid=()=>crypto.randomUUID();
async function sha(v){return b64u(await crypto.subtle.digest("SHA-256",typeof v==="string"?enc.encode(v):v))}
async function hmac(secret,v){const k=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64u(await crypto.subtle.sign("HMAC",k,enc.encode(v)))}
function eq(a,b){if(typeof a!=="string"||typeof b!=="string")return false;const x=enc.encode(a),y=enc.encode(b);if(x.length!==y.length)return false;let d=0;for(let i=0;i<x.length;i++)d|=x[i]^y[i];return d===0}
function json(x,status=200,headers={}){return new Response(JSON.stringify(x),{status,headers:{"content-type":"application/json;charset=utf-8",...headers}})}
function api(ok,data,error,requestId,status=200,debug=null){return json({success:ok,data:ok?data:null,error:ok?null:error,requestId,...(debug?{debug}: {})},status)}
function err(code,message,status,stage,details={}){return {code,message,status,stage,details}}
function origin(req){return req.headers.get("Origin")||""} function ip(req){return req.headers.get("CF-Connecting-IP")||"0.0.0.0"}
function ua(req){return req.headers.get("User-Agent")||""}
function cookies(req){const o={},raw=req.headers.get("Cookie")||"";for(const p of raw.split(";")){const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function allowed(env){return String(env.ALLOWED_ORIGINS||"").split(",").map(x=>x.trim()).filter(Boolean)}
function allowedOrigin(req,env){const o=origin(req),a=allowed(env);if(!o)return true;return a.length? a.includes(o):o===new URL(req.url).origin}
function cookie(name,value,maxAge,httpOnly,sameSite){return `${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; Secure; ${httpOnly?"HttpOnly; ":""}SameSite=${sameSite}`}
function sec(){return {"X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","X-Frame-Options":"DENY","Permissions-Policy":"camera=(), microphone=(), geolocation=()","Cache-Control":"no-store"}}
function secure(r,extra={}){const h=new Headers(r.headers);for(const[k,v]of Object.entries(sec()))h.set(k,v);for(const[k,v]of Object.entries(extra))h.set(k,v);return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}
function debugOn(env){return env.AUTH_DEBUG===true||env.AUTH_DEBUG==="true"}
async function debugLog(env,{request,requestId,event,stage,status=200,code=null,message=null,details={}}){if(!debugOn(env))return;try{await env.DB.prepare(`INSERT INTO debug_logs(id,request_id,event,stage,method,path,origin,status,code,message,details_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(uuid(),requestId,event,stage,request.method,new URL(request.url).pathname,origin(request)||null,status,code,message?String(message).slice(0,1000):null,JSON.stringify(details),now()).run()}catch(e){console.error("debug_log_failed",requestId,e?.message)}}
async function ctxHash(env,v){const s=env.AUDIT_HASH_SECRET||env.SESSION_SECRET;if(!s)throw new Error("Missing AUDIT_HASH_SECRET/SESSION_SECRET");return hmac(s,v)}
async function audit(env,{userId=null,eventType,success=true,requestId,request}){try{await env.DB.prepare(`INSERT INTO audit_logs(id,user_id,event_type,success,ip_hash,user_agent_hash,request_id,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(uuid(),userId,eventType,success?1:0,await ctxHash(env,ip(request)),await ctxHash(env,ua(request)),requestId,JSON.stringify({method:request.method,path:new URL(request.url).pathname}),now()).run()}catch(e){console.error("audit_failed",requestId,e?.message)}}
async function pwHash(p,s,it){const key=await crypto.subtle.importKey("raw",enc.encode(p),"PBKDF2",false,["deriveBits"]);return b64u(await crypto.subtle.deriveBits({name:"PBKDF2",salt:fromB64u(s),iterations:it,hash:"SHA-256"},key,256))}
async function makePw(p,env){const salt=b64u(rand(16)),it=Number(env.PBKDF2_ITERATIONS||CONFIG.PBKDF2_ITERATIONS);return{salt,hash:await pwHash(p,salt,it),iterations:it}}
async function rate(env,key,name="AUTH_RATE_LIMIT"){const l=env[name];if(!l)return true;try{return !!(await l.limit({key})).success}catch(e){console.error("rate_limit_error",name,e?.message);return true}}
function validPw(p){return typeof p==="string"&&p.length>=CONFIG.PASSWORD_MIN_LENGTH&&p.length<=CONFIG.MAX_PASSWORD_LENGTH}
function norm(v){return String(v||"").trim().toLowerCase()}
async function userById(db,id){return db.prepare(`SELECT * FROM users WHERE id=? LIMIT 1`).bind(id).first()}
async function userByIdentifier(db,id){const n=norm(id);return db.prepare(`SELECT * FROM users WHERE (username IS NOT NULL AND lower(username)=?) OR (email IS NOT NULL AND lower(email)=?) LIMIT 1`).bind(n,n).first()}
async function session(env,userId,request){if(!env.SESSION_SECRET)throw new Error("SESSION_SECRET is required");const t=token(),h=await sha(t),id=uuid(),n=now(),e=add(Number(env.SESSION_TTL_SECONDS||CONFIG.SESSION_TTL_SECONDS));await env.DB.prepare(`INSERT INTO sessions(id,user_id,token_hash,created_at,expires_at,last_seen_at,ip_hash,user_agent_hash) VALUES(?,?,?,?,?,?,?,?)`).bind(id,userId,h,n,e,n,await ctxHash(env,ip(request)),await ctxHash(env,ua(request))).run();return{token:t,expiresAt:e}}
async function getSession(env,req){const t=cookies(req)[CONFIG.COOKIE_NAME];if(!t)return null;const r=await env.DB.prepare(`SELECT s.*,u.status,u.username,u.email,u.phone FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.status='active' LIMIT 1`).bind(await sha(t),now()).first();if(r)await env.DB.prepare(`UPDATE sessions SET last_seen_at=? WHERE id=?`).bind(now(),r.id).run();return r}
function csrfCheck(req,env){if(["GET","HEAD","OPTIONS"].includes(req.method))return{ok:true,reason:"safe_method"};if(!allowedOrigin(req,env))return{ok:false,reason:"origin_denied"};const c=cookies(req)[CONFIG.CSRF_COOKIE],h=req.headers.get("X-CSRF-Token");if(!c)return{ok:false,reason:"csrf_cookie_missing"};if(!h)return{ok:false,reason:"csrf_header_missing"};if(!eq(c,h))return{ok:false,reason:"csrf_mismatch"};return{ok:true,reason:"ok"}}
async function csrf(req,env,id){const t=token();await debugLog(env,{request:req,requestId:id,event:"CSRF_ISSUED",stage:"issue_csrf",details:{sameSite:env.COOKIE_SAMESITE||"None",origin:origin(req)||null}});return secure(api(true,{csrfToken:t,config:publicConfig(env)},null,id),{"Set-Cookie":cookie(CONFIG.CSRF_COOKIE,t,Number(env.CSRF_TTL_SECONDS||CONFIG.CSRF_TTL_SECONDS),false,env.COOKIE_SAMESITE||"None")})}
function publicConfig(env){return{appName:env.APP_NAME||CONFIG.APP_NAME,successRedirect:env.LOGIN_SUCCESS_REDIRECT||CONFIG.LOGIN_SUCCESS_REDIRECT,smsEnabled:env.SMS_ENABLED===true||env.SMS_ENABLED==="true",smsProvider:env.SMS_PROVIDER||null,oidcEnabled:env.OIDC_ENABLED===true||env.OIDC_ENABLED==="true",debug:debugOn(env)}}
async function login(req,env,id){const c=csrfCheck(req,env);if(!c.ok){await debugLog(env,{request:req,requestId:id,event:"LOGIN_REJECTED",stage:"csrf",status:403,code:"CSRF_FAILED",message:c.reason,details:{origin:origin(req)||null,cookiePresent:!!cookies(req)[CONFIG.CSRF_COOKIE],headerPresent:!!req.headers.get("X-CSRF-Token")}});return api(false,null,err("CSRF_FAILED","درخواست نامعتبر است.",403,"csrf",{reason:c.reason,origin:origin(req)||null}),id,403,debugOn(env)?{stage:"csrf",reason:c.reason}:null)}
 if(!(await rate(env,`password:ip:${ip(req)}`)))return api(false,null,err("RATE_LIMITED","تعداد درخواست‌ها بیش از حد مجاز است.",429,"rate_limit"),id,429);const body=await req.json().catch(()=>null),identifier=String(body?.identifier||"").trim(),password=body?.password;if(!validPw(password))return api(false,null,err("AUTHENTICATION_FAILED","نام کاربری یا رمز عبور صحیح نیست",401,"input"),id,401);const u=await userByIdentifier(env.DB,identifier);let ok=false,reason="invalid_credentials";if(u){const cr=await env.DB.prepare(`SELECT * FROM user_credentials WHERE user_id=?`).bind(u.id).first();const locked=u.locked_until&&u.locked_until>now();if(cr&&!locked)ok=eq(await pwHash(password,cr.password_salt,Number(cr.hash_iterations)),cr.password_hash);else if(locked)reason="account_locked"}
 if(!ok){if(u){const n=Number(u.failed_login_count||0)+1;await env.DB.prepare(`UPDATE users SET failed_login_count=?,locked_until=?,updated_at=? WHERE id=?`).bind(n,n>=8?add(300):null,now(),u.id).run()}await debugLog(env,{request:req,requestId:id,event:"LOGIN_FAILED",stage:"credentials",status:401,code:"AUTHENTICATION_FAILED",message:reason,details:{userFound:!!u}});return api(false,null,err("AUTHENTICATION_FAILED","نام کاربری یا رمز عبور صحیح نیست",401,"credentials",{reason}),id,401,debugOn(env)?{stage:"credentials",reason}:null)}
 await env.DB.prepare(`UPDATE users SET failed_login_count=0,locked_until=NULL,last_login_at=?,updated_at=? WHERE id=?`).bind(now(),now(),u.id).run();const s=await session(env,u.id,req);await audit(env,{userId:u.id,eventType:"LOGIN_SUCCESS",success:true,requestId:id,request:req});await debugLog(env,{request:req,requestId:id,event:"LOGIN_SUCCESS",stage:"session_created",details:{userId:u.id}});return secure(api(true,{redirect:env.LOGIN_SUCCESS_REDIRECT||CONFIG.LOGIN_SUCCESS_REDIRECT,expiresAt:s.expiresAt},null,id),{"Set-Cookie":cookie(CONFIG.COOKIE_NAME,s.token,Number(env.SESSION_TTL_SECONDS||CONFIG.SESSION_TTL_SECONDS),true,env.COOKIE_SAMESITE||"None")})}
async function debugLogs(req,env,id){if(!debugOn(env))return api(false,null,err("NOT_FOUND","مسیر موردنظر پیدا نشد.",404,"debug_disabled"),id,404);const u=new URL(req.url),limit=Math.min(Number(u.searchParams.get("limit")||50),200);const r=await env.DB.prepare(`SELECT id,request_id,event,stage,method,path,origin,status,code,message,details_json,created_at FROM debug_logs ORDER BY created_at DESC LIMIT ?`).bind(limit).all();return secure(api(true,{logs:r.results||[]},null,id))}
async function debugClear(req,env,id){if(!debugOn(env))return api(false,null,err("NOT_FOUND","مسیر موردنظر پیدا نشد.",404,"debug_disabled"),id,404);await env.DB.prepare(`DELETE FROM debug_logs`).run();return secure(api(true,{cleared:true},null,id))}
async function route(req,env,id){const p=new URL(req.url).pathname;if(p==="/api/auth/v1/config"&&req.method==="GET")return secure(api(true,publicConfig(env),null,id));if(p==="/api/auth/v1/csrf"&&req.method==="GET")return csrf(req,env,id);if(p==="/api/auth/v1/login/password"&&req.method==="POST")return login(req,env,id);if(p==="/api/auth/v1/session"&&req.method==="GET"){const s=await getSession(env,req);return secure(api(true,s?{authenticated:true,user:{id:s.user_id,username:s.username,email:s.email,phone:s.phone},expiresAt:s.expires_at}:{authenticated:false},null,id))}if(p==="/api/auth/v1/logout"&&req.method==="POST"){const c=csrfCheck(req,env);if(!c.ok)return api(false,null,err("CSRF_FAILED","درخواست نامعتبر است.",403,"csrf",{reason:c.reason}),id,403);const s=await getSession(env,req);if(s)await env.DB.prepare(`UPDATE sessions SET revoked_at=? WHERE id=?`).bind(now(),s.id).run();return secure(api(true,{loggedOut:true},null,id),{"Set-Cookie":cookie(CONFIG.COOKIE_NAME,"",0,true,"Lax")})}if(p==="/api/auth/v1/debug/logs"&&req.method==="GET")return debugLogs(req,env,id);if(p==="/api/auth/v1/debug/clear"&&req.method==="POST")return debugClear(req,env,id);return null}
export{makePw as createPasswordHash};
export default{async fetch(req,env){const id=uuid();const start=Date.now();try{if(req.method==="OPTIONS"){if(!allowedOrigin(req,env))return secure(new Response(null,{status:403}));const o=origin(req)||new URL(req.url).origin;return secure(new Response(null,{status:204,headers:{"Access-Control-Allow-Origin":o,"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type, X-CSRF-Token","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"}}))}if(!allowedOrigin(req,env)){await debugLog(env,{request:req,requestId:id,event:"REQUEST_REJECTED",stage:"origin",status:403,code:"ORIGIN_DENIED",message:"Origin not allowed",details:{origin:origin(req)||null}});return secure(api(false,null,err("ORIGIN_DENIED","درخواست نامعتبر است.",403,"origin",{origin:origin(req)||null}),id,403))}const r=await route(req,env,id);if(r){const h={};if(origin(req))Object.assign(h,{"Access-Control-Allow-Origin":origin(req),"Access-Control-Allow-Credentials":"true","Vary":"Origin"});await debugLog(env,{request:req,requestId:id,event:"REQUEST_COMPLETE",stage:"route",status:r.status,details:{durationMs:Date.now()-start}});return secure(r,h)}const u=new URL(req.url);if(env.ASSETS)return secure(await env.ASSETS.fetch(req));return secure(new Response("Not Found",{status:404}))}catch(e){console.error("request_error",id,e?.stack||e?.message);await debugLog(env,{request:req,requestId:id,event:"REQUEST_EXCEPTION",stage:"unhandled",status:500,code:"INTERNAL_ERROR",message:e?.message||"unknown",details:{name:e?.name||null,stack:debugOn(env)?String(e?.stack||"").slice(0,4000):undefined,durationMs:Date.now()-start}});return secure(api(false,null,err("INTERNAL_ERROR","خطایی رخ داد. لطفاً دوباره تلاش کنید.",500,"unhandled",debugOn(env)?{message:e?.message||"unknown",name:e?.name||null}:{}),id,500,debugOn(env)?{stage:"unhandled",message:e?.message||"unknown"}:null))}}};
